### ISSUE TITLE
Feedback: Lab 2: Using Higher Order Functions (3-lists)

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#111]
#### [View the Page here](http://bjc.edc.org/bjc-r/cur/programming/3-lists/3-using-hof/getting-started.html?topic=nyc_bjc%2F3-lists.topic&course=bjc4nyc_2015-2016.html&novideo&noassignment)

---

Lab 2: Using Higher Order Functions
Shouldn't the title be Lab 3: Using Higher Order Functions?
http://bjc.edc.org/bjc-r/cur/programming/3-lists/3-using-hof/getting-started.html?topic=nyc_bjc%2F3-lists.topic&course=bjc4nyc_2015-2016.html&novideo&noassignment

**Comment by jkangEDC** [comment]
fixed
