### ISSUE TITLE
Feedback: Timing Sum-thing's Up (4-algorithms)

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#130]
#### [View the Page here](http://bjc.edc.org/bjc-r/cur/programming/algorithms/timing/timing-sum-things-up.html?topic=nyc_bjc%2F4-algorithms.topic&course=bjc4nyc_2015-2016.html&noassignment&novideo)

---

The two block images shown on the page differ from the blocks in the Snap! project for this lab (in the lab, they don't have the input spaces or the word "in"). They also differ from the descriptions lower on the page, which describe "add all numbers between 1 and max" instead of "add all numbers in list"

**Comment by maryfries** [comment]
Is this page in U4 anymore?

**Comment by maryfries** [comment]
added as html comment
