### ISSUE TITLE
Feedback: Video Lecture: Abstraction (1-intro-loops)

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#137]
#### [View the Page here](http://bjc.edc.org/bjc-r/llab/html/empty-curriculum-page.html?topic=nyc_bjc%2F1-intro-loops.topic&src=https%3A%2F%2Fcoursesharing.org%2Fcourses%2F6%2Flectures%2F7&title=Video%20Lecture%3A%20Abstraction)

---

There is no video.

**Comment by maryfries** [comment]
This is an old page we don't manage. Old pages should be deleted.

**Comment by cycomachead** [comment]
This link used to be in the topic file for U1 but was removed.

https://github.com/bjc-edc/bjc-r/commit/93805f37f08c61d7bacfedcd088b042e43a84a7f#diff-012c5f998bafcc757b6521975fd38326L5

**Comment by maryfries** [comment]
ok to close this then?
