### ISSUE TITLE
Feedback: Video Lecture: Abstraction (1-intro-loops)

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#139]
#### [View the Page here](https://bjc.edc.org/bjc-r/llab/html/empty-curriculum-page.html?topic=nyc_bjc%2F1-intro-loops.topic&src=https%3A%2F%2Fcoursesharing.org%2Fcourses%2F6%2Flectures%2F7&title=%20Video%20Lecture%3A%20Abstraction%20)

---

Video cannot be viewed in the page or in its own window.

I got to this page using IE. LInk was at the top of page https://edge.edx.org/courses/course-v1:BerkeleyX+BJCx.1+2015/courseware/de4a08b5899f4a59b99a0f909b99d924/da305f5415c3403681223f57b2fd729e/

When I open the source page in Firefox, the link to the video is not there, but instead there's a link to the course page.

**Comment by maryfries** [comment]
We need to remove the old course files. I was just talking about this with Brian this morning. The repo is too big, and we only use a bit of it. There is also this problem...

**Comment by cycomachead** [comment]
Something must have happened with the way the course got embedded in edX, but this video link was removed from the topic file
https://github.com/bjc-edc/bjc-r/commit/93805f37f08c61d7bacfedcd088b042e43a84a7f#diff-012c5f998bafcc757b6521975fd38326L5

There's probably an open question of what to do about linking to videos in the topic files.

As far as deleting content -- that can't really be done very easily, or it will make it harder to merge content back together, though I guess at this point it seems like that isn't very likely to happen.

**Comment by maryfries** [comment]
Is there anything to do with this comment or should we just close it?

**Comment by cycomachead** [comment]
I don't think so.
