### ISSUE TITLE
Feedback: Lab 1 Check: Lists (3-lists)

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#149]
#### [View the Page here](http://bjc.edc.org/bjc-r/cur/programming/3-lists/1-introduction-to-lists/lists-self-test.html?topic=nyc_bjc%2F3-lists.topic&course=bjc4nyc_2015-2016.html&novideo&noassignment)

---

When items b, c & e are selected and check answer is clicked
Answers for b c d & e are displayed 
Even though item d was not selectd?

**Comment by maryfries** [comment]
added html comment
