### ISSUE TITLE
Feedback: More Fractals (5-recursion-trees-fractals)

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#163]
#### [View the Page here](http://bjc.edc.org/bjc-r/cur/programming/5-recursion/2-fractals/c-curve.html?topic=nyc_bjc%2F5-recursion-trees-fractals.topic&course=bjc4nyc_2015-2016.html&novideo&noassignment)

---

I like this program.  I needed Brian Harvey's help to understand the fractal and thus be able to write this program.  I know it sounds silly, but the colors threw me off!  The base level was red and the next level is a red and blue corner.  The next level should be the red and blue corner and then ANOTHER red and blue corner.  The coloring messed with my noggin.

**Comment by maryfries** [comment]
entered as html comment
