### ISSUE TITLE
Feedback: Sorting (6-recursive-reporters)

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#166]
#### [View the Page here](http://bjc.edc.org/bjc-r/cur/programming/6-recursive-reporters/4-sorting/recursively-sorting.html?topic=nyc_bjc%2F6-recursive-reporters.topic&course=bjc4nyc_2015-2016.html&novideo&noassignment)

---

Why is the easiest way to split the data in half to collect odd and even numbers? Could you explain that rationale?  It seems like it would be easier to just divide the list in two...

**Comment by maryfries** [comment]
added as html comment
