### ISSUE TITLE
Feedback: Visualizing the Data in Snap! (3-lists)

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#178]
#### [View the Page here](http://bjc.edc.org/bjc-r/cur/programming/3-lists/5-search-and-data/gps-digital-forensics/visualizing.html?topic=nyc_bjc%2F3-lists.topic&course=bjc4nyc_2015-2016.html&novideo&noassignment)

---

I'm not sure what the case is, or what the students are being directed to do.  What are examples of hypotheses they might have? What is the situation?

**Comment by maryfries** [comment]
Added as html comment
