### ISSUE TITLE
Feedback: The Data (3-lists)

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#180]
#### [View the Page here](http://bjc.edc.org/bjc-r/cur/programming/3-lists/5-search-and-data/spam-ham/2-the-data.html?topic=nyc_bjc%2F3-lists.topic&course=bjc4nyc_2015-2016.html&novideo&noassignment)

---

There is a spelling error after the graphic of the list.  It should be "language" not "langauge"

**Comment by maryfries** [comment]
fixed
