### ISSUE TITLE
Feedback: Unit 1 Investigations Teacher Guide (1-teaching-guide)

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#201]
#### [View the Page here](http://bjc.edc.org/bjc-r/cur/teaching-guide/U1/investigations/bug-dance.html?topic=nyc_bjc%2F1-teaching-guide.topic&course=bjc4nyc_2015-2016_teacher.html&novideo&noassignment)

---

I just wanted to say that the explicit correlation to CSP found on this page is terrific. Also, on a previous page I saw a detailed breakdown of first day events with timing suggestions. While my mileage may vary, this is so helpful as I get back to thinking about an actual class in a couple days.

**Comment by maryfries** [comment]
this page was actually cut...
