### ISSUE TITLE
Feedback: Experiencing Algorithms (4-algorithms)

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#213]
#### [View the Page here](http://bjc.edc.org/bjc-r/cur/programming/algorithms/experiencing-algorithms.html?topic=nyc_bjc%2F4-algorithms.topic&course=bjc4nyc_2015-2016.html&novideo&noassignment)

---

Change "We're" to "You're"!

**Comment by maryfries** [comment]
entered html comment
