### ISSUE TITLE
Feedback: Investgations (3-lists)

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#249]
#### [View the Page here](http://bjc.edc.org/bjc-r/cur/programming/3-lists/investigations/display-word.html?topic=nyc_bjc%2F3-lists.topic&course=bjc4nyc_2015-2016.html&novideo&noassignment)

---

(this is Dan Garcia) I thought  we were getting rid of Hangman!

**Comment by maryfries** [comment]
I thought we did. Where is he finding this link? (I asked in an email.)

**Comment by maryfries** [comment]
There is no reference to this page on the entire site.
