### ISSUE TITLE
Feedback: Lab 1: List Manipulation (5-algorithms)

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#274]
#### [View the Page here](http://bjc.edc.org/bjc-r/cur/programming/5-algorithms/1-list-manipulation/3-algorithms-in-snap.html?topic=nyc_bjc%2F5-algorithms.topic&course=bjc4nyc_2015-2016.html&novideo&noassignment)

---

It would be really helpful if the graphic included the _indices_ of the items in the list. A lot of people fail to make the distinction between between the position and the value.

**Comment by maryfries** [comment]
entered as html comment
