### ISSUE TITLE
Feedback: Algorithmic Complexity (algorithm-complexity)

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#34]
#### [View the Page here](http://bjc.berkeley.edu/bjc-r/llab/html/empty-curriculum-page.html?topic=berkeley_bjc%2Fareas%2Falgorithm-complexity.topic&src=https%3A%2F%2Fcoursesharing.org%2Fcourses%2F6%2Flectures%2F15&title=%20Algorithmic%20Complexity%20)

---

"The server refused the connection."  Please fix.

**Comment by maryfries** [comment]
I'm guessing that this happened because of a school firewall of some kind...

Perhaps we could include a link to the video for those in that situation?

Also, YouTube is definitely risky for schools in general; many block it.

**Comment by cycomachead** [comment]
This one is pointing to a Berkeley link for some reason.. The videos aren't currently used in any of the EDC labs I think. 

The site that was hosting the videos was down for a long time. (I actually thought it was down for good.)

There is a link below the video though to open in a new window.
