### ISSUE TITLE
Feedback: Unit 3 Lab 5: Search (3-lists)

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#371]
#### [View the Page here](http://bjc.edc.org/bjc-r/cur/programming/3-lists/5-search-internet/getting-started.html?topic=nyc_bjc%2F3-lists.topic&course=bjc4nyc_2015-2016.html&novideo&noassignment)

---

test one two three, one of the teachers said this didn't work.

**Comment by maryfries** [comment]
entered as html comment
