### ISSUE TITLE
Feedback: Unit 4 Lab 4: GPS Forensics (4-internet)

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#392]
#### [View the Page here](http://bjc.edc.org/bjc-r/cur/programming/4-internet/4-gps-data/2-visualizing.html?topic=nyc_bjc%2F4-internet.topic&course=bjc4nyc_2015-2016.html&novideo&noassignment)

---

The previous page "Introduction" yields the following error: Not Found

The requested URL /bjc-r/cur/programming/4-internet/4-gps-data/1-introgps.html was not found on this server.

this page does not seem to tell the student anything about where to get data.  It is very confusing to be asked to visualize data when you have none.

**Comment by maryfries** [comment]
entered as html comment
