### ISSUE TITLE
Feedback: Pair Programming (1-intro-loops)

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#41]
#### [View the Page here](http://bjc.edc.org/bjc-r/cur/programming/guides/pair-programming-intro.html?topic=nyc_bjc%2F1-intro-loops.topic&course=bjc4nyc_2015-2016.html&novideo&noreading&noassignment)

---

The link on this page is broken.

**Comment by maryfries** [comment]
This page is no longer part of U1.
