### ISSUE TITLE
Feedback: Lab 3: Timing Experiments (5-algorithms)

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#430]
#### [View the Page here](http://bjc.edc.org/bjc-r/cur/programming/5-algorithms/3-timing-experiments/7-timing-sum-things-up.html?topic=nyc_bjc%2F5-algorithms.topic&course=bjc4nyc_2015-2016.html&noassignment&novideo)

---

more detail

**Comment by maryfries** [comment]
Again, this page is not in the curriculum; where are people getting the link?
