### ISSUE TITLE
Feedback: Lab 3: Timing Experiments (5-algorithms)

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#435]
#### [View the Page here](http://bjc.edc.org/bjc-r/cur/programming/5-algorithms/3-timing-experiments/7-timing-sum-things-up.html?topic=nyc_bjc%2F5-algorithms.topic&course=bjc4nyc_2015-2016.html&noassignment&novideo)

---

more detail with image

**Comment by maryfries** [comment]
This page is not in the curriculum (it's just on the server somewhere; I'll clean it off). But where are people getting the link?
