### ISSUE TITLE
Feedback: Unit 4 Lab 4: Network Protocols, Page 1 (4-internet)

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#440]
#### [View the Page here](http://bjc-edc.github.io/bjc-r/cur/programming/4-internet/4-protocols/1-ip-routing.html?topic=nyc_bjc%2F4-internet.topic&course=bjc4nyc_2015-2016.html&novideo&noassignment)

---

Instead of duckduckgo's query, just use

http://bot.whatismyipaddress.com/

which returns the IP address plain and simple.

dan

**Comment by maryfries** [comment]
entered comment
