### ISSUE TITLE
Feedback: Unit 3 Lab 2: Nesting Lists, Page 4 (3-lists)

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#456]
#### [View the Page here](http://bjc.edc.org/bjc-r/cur/programming/3-lists/2-nesting-lists/4-contact-list-app-2.html?topic=nyc_bjc%2F3-lists.topic&course=bjc4nyc_2015-2016.html&novideo&noassignment)

---

I don't feel that this page explains the need for constructor and selector blocks very well.  I had to read through this several times before I could articulate why this method was not redundancy.  If you add complexity to the contact, the constructor block WOULD have to be changed.  So would the selector blocks so that they pull the right item from a contact.  The only benefit to creating these blocks is if other programs were to use them.  Instead of having to change the item number when selecting.... But I don't think you get that from this page....

**Comment by maryfries** [comment]
entered html comment
