### ISSUE TITLE
Feedback: Unit 3 Lab 6: Encryption, Page 1 (3-lists)

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#460]
#### [View the Page here](http://bjc.edc.org/bjc-r/cur/programming/3-lists/6-encryption/1-getting-started.html?topic=nyc_bjc%2F3-lists.topic&course=bjc4nyc_2015-2016.html&novideo&noassignment)

---

My 2 cents:  The encode and decode scripts should be here instead of in previous labs. The kids didn't know what unicode was when they created them.

**Comment by maryfries** [comment]
entered html comment
