### ISSUE TITLE
Feedback: Unit 1 Lab 4: Building and Debugging Your Own Blocks, Page 3 (1-intro-loops)

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#467]
#### [View the Page here](http://bjc.edc.org/bjc-r/cur/programming/1-introduction/4-building-and-debugging/3-debugging-custom-blocks.html?topic=nyc_bjc%2F1-intro-loops.topic&course=bjc4nyc_2015-2016.html&novideo&noassignment)

---

this page would work better if you gave the students the sample scripts, unless you want them to practice building scripts still

**Comment by maryfries** [comment]
entered html comment
