### ISSUE TITLE
Feedback: Unit 5 Lab 4: Unsolvable and Undecidable Problems, Page 1 (5-algorithms)

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#470]
#### [View the Page here](http://bjc.edc.org/bjc-r/cur/programming/5-algorithms/4-unsolvable-undecidable/1-logical-inconsistency.html?topic=nyc_bjc%2F5-algorithms.topic&course=bjc4nyc_2015-2016.html&novideo&noassignment)

---

Fix the For You to Do, #1. The wording makes it sound possible for there to be multiple families, not just the two. In addition, #2 is grammatically incorrect. Derek is not an adjective.

**Comment by maryfries** [comment]
entered html comment for problem 1 
fixed problem 2
