### ISSUE TITLE
Feedback: Unit 4 Lab 8: Innovating for Social Change, Page 2 (4-internet)

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#473]
#### [View the Page here](http://bjc.edc.org/bjc-r/cur/programming/4-internet/8-innovations/2-address-the-issue.html?topic=nyc_bjc%2F4-internet.topic&course=bjc4nyc_2015-2016.html&novideo&noassignment)

---

Has this been updated for the most recent version of the AP task?

**Comment by maryfries** [comment]
entered html comment
