### ISSUE TITLE
Feedback: Unit 5 Lab 7: Copyrights and Patents, Page 8 (5-algorithms)

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#479]
#### [View the Page here](https://bjc.edc.org/bjc-r/cur/programming/5-algorithms/7-copyrights-and-patents/8-digital.html?topic=nyc_bjc%2F5-algorithms.topic&course=bjc4nyc_2015-2016.html&novideo&noassignment)

---

BREAK THIS PAGE INTO SECTIONS TO NOT MAKE IT A WHOLE BIG CHUNK

**Comment by maryfries** [comment]
entered html comment
