### ISSUE TITLE
Responsive Design Issues

### ISSUE THREAD

**Issue by maryfries** [bjc-edc/bjc-r#53]
I noticed that if the window gets too narrow, the whole title bar disappears (logo, title, back/next buttons) except for the three line menu. That's not ideal, but what appears in the menu is not particularly readable:

![image](https://user-images.githubusercontent.com/6549787/130308321-dea10105-cbb7-4942-8fad-7e082f589eaf.png)

**Comment by cycomachead** [comment]
The top text disappearing is entirely intentional. The menu thing I assume changed when the navigation color changed. I’ll see if I can fix that though I assume this has also been broken a while.
