### ISSUE TITLE
Feedback: Lab 5 Check: Building Complicated Blocks with Simple Blocks (1-intro-loops)

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#55]
#### [View the Page here](http://bjc.edc.org/bjc-r/cur/programming/1-introduction/5-building-complicated-blocks/buggy-house-and-square-self-test.html?topic=nyc_bjc%2F1-intro-loops.topic&course=bjc4nyc_2015-2016.html&noassignment&noreading&novideo)

---

the buggy block is the same

**Comment by maryfries** [comment]
I don't know what this means. Michael, did you leave this comment or is it something entered through the feedback form that we cannot trace?

**Comment by maryfries** [comment]
ok, this page needs attention anyway...
