### ISSUE TITLE
Feedback: Lab 3 Check: Using the Repeat Block (1-intro-loops)

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#57]
#### [View the Page here](http://bjc.edc.org/bjc-r/cur/programming/1-introduction/3-repeating-commands/repeat-self-test.html?1&1&1&2&2&topic=nyc_bjc%2F1-intro-loops.topic&course=bjc4nyc_2015-2016.html&novideo&noreading&noassignment)

---

More quizzes like this would be amazing!!!

**Comment by maryfries** [comment]
added as a html comment
