### ISSUE TITLE
Feedback: Lab 6 Check: Using Randomness (1-intro-loops)

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#60]
#### [View the Page here](http://bjc.edc.org/bjc-r/cur/programming/1-introduction/6-using-randomness/random-self-test.html?topic=nyc_bjc%2F1-intro-loops.topic&course=bjc4nyc_2015-2016.html&noassignment&noreading&novideo)

---

question3 is too small

**Comment by maryfries** [comment]
added as an html comment
