### ISSUE TITLE
Feedback: Lab 5 Check: Building Complicated Blocks with Simple Blocks (1-intro-loops)

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#61]
#### [View the Page here](http://bjc.edc.org/bjc-r/cur/programming/1-introduction/5-building-complicated-blocks/buggy-house-and-square-self-test.html?1&1&1&2&2&2&3&3&3&topic=nyc_bjc%2F1-intro-loops.topic&course=bjc4nyc_2015-2016.html&novideo&noreading&noassignment)

---

The formatting of the questions does not seem right. There are some phrases in parentheses which I'm not sure are supposed to be there.

**Comment by maryfries** [comment]
added as a html comment
