### ISSUE TITLE
Feedback: Lab 9: Programs with Multiple Sprites (2-conditionals-abstraction)

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#88]
#### [View the Page here](http://bjc.edc.org/bjc-r/cur/programming/2-conditionals-abstraction-testing/9-programs-with-multiple-sprites/snap-play-learn-broadcast.html?topic=nyc_bjc%2F2-conditionals-abstraction.topic&course=bjc4nyc_2015-2016.html&novideo&noreading&noassignment)

---

You reference play sound blocks that were used in previous labs but none were presented before this page.

**Comment by maryfries** [comment]
Where did this page come from? The U1/U2 team is unfamiliar with this content...
