### ISSUE TITLE
Lab 1: Conditional Blocks (2-conditionals-abstraction) Extend "Take It Further"

### ISSUE THREAD

**Issue by cycomachead** [bjc-edc/bjc-r#97]
#### [View the Page here](http://bjc.edc.org/bjc-r/cur/programming/2-conditionals-abstraction-testing/1-conditionals/1-getting-started-with-conditionals.html?topic=nyc_bjc%2F2-conditionals-abstraction.topic&course=bjc4nyc_2015-2016.html&novideo&noassignment)

---

(this is Dan Garcia) Take it further 4 has the interesting feature that you can change the repeat blocks to have values that don't add to 360, but say add to 90, you get a beautiful tiger pattern.  Like this http://snap.berkeley.edu/snapsource/snap.html#present:Username=dan%20garcia&ProjectName=Tiger  and if they don't add to a number that 360 is a multiple of, the tiger pattern "moves".  So there's potential for a nice conversation (which we went into in NYC) how to get the tiger pattern with the if/else that the repeat was able to give.  Great followups questions 4a and 4b.

**Comment by cycomachead** [comment]
Dan, if you ever write you github username @ddgarcia you'll get notified of any comments / updates on an issue. (True of edc labs or our CS10 ones).

**Comment by maryfries** [comment]
Added as HTML comment on page.
